### ISSUE TITLE
https://easy-mock.com/docs 挂了

### ISSUE THREAD

**Issue by Simlan** [easy-mock/easy-mock#282]
https://easy-mock.com/docs 挂了

**Comment by xmskying** [comment]
整个站都挂了

**Comment by mschenyu** [comment]
一上午了还没恢复。。。。

**Comment by yffs89** [comment]
。。。。。。。。。

**Comment by qingjuesama** [comment]
什么时候恢复啊...

**Comment by Simlan** [comment]
哈哈，挂一下，检验一下有多少人在用

**Comment by zhangxiongfeng** [comment]
+1

**Comment by xmskying** [comment]
已恢复




    


在2019年01月31日 15:10，Alerta 写道： +1

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/easy-mock/easy-mock","title":"easy-mock/easy-mock","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/easy-mock/easy-mock"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhangxiongfeng in #282: +1"}],"action":{"name":"View Issue","url":"https://github.com/easy-mock/easy-mock/issues/282#issuecomment-459239999"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/easy-mock/easy-mock/issues/282#issuecomment-459239999",
"url": "https://github.com/easy-mock/easy-mock/issues/282#issuecomment-459239999",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chuangker** [comment]
#92
